### ISSUE TITLE
Beadandó

### ISSUE THREAD

**Issue by Rumkokos05** [Teaching-projects/januari-beadando-Rumkokos05#2]
januári beadandó program javítva, magyarázó változók hozzáadva

**Comment by hegyhati** [comment]
Alap beadandonak rendben van, jobb jegyekert azert valami osszetettebbet kellene. 
Mivel a programnak nagyon nincs semmi "hattertortenete", csak szimplan ad egy random szamot 1 es n kozott, ezert nehez hozza barmit mondani. 
Egy masik dolog, hogy ezt a mukodest azert kb fele ennyi sorbol is kenyelmesen (es szebben) meg lehet csinalni, egy refactort javaslok.

**Comment by hegyhati** [comment]
2
